server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application.name: library-management-system-spring-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library_management_system_db
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: simple



logging:
  level:
    org:
      springframework:
        cache: trace
        web.filter.CommonsRequestLoggingFilter: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html

